In [21]:
#1.3.1
import numpy as np
# создаем массив нулей 8х8
array = np.zeros((8, 8))
# заполняем его в шахматном порядке
array[1::2, ::2] = 1
array[::2, 1::2] = 1
print(array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [26]:
#1.3.2
import numpy as np
# создаем массив нулей 5х5 и с помощью сложения матриц прибавляем матрицу 0х5 
array = np.zeros((5, 5))+np.arange(0, 5)
print(array)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [27]:
#1.3.3
import numpy as np
# создаем трехмерную матрицу со случаными числами от 0 до 1
array = np.random.random((3,3,3))
print(array)

[[[0.52210683 0.38211519 0.7412039 ]
  [0.73129836 0.55241551 0.13093659]
  [0.92733666 0.88494522 0.74602677]]

 [[0.93710825 0.60645889 0.15914039]
  [0.73577661 0.82054205 0.79695898]
  [0.55083639 0.87775216 0.10218691]]

 [[0.538138   0.69853793 0.81685518]
  [0.13837118 0.89208151 0.33042428]
  [0.99632485 0.776359   0.33592556]]]


In [31]:
#1.3.4
import numpy as np
# создаем массив единиц 10х10
array = np.ones((10, 10))
# заполняем строчки от 1 до n-1 и все столбцы от 1 до n-1 - нулями 
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [33]:
#1.3.5
import numpy as np
array = np.random.random(10)
print(f"array: {array}")
array[::-1].sort()
print(f"sorted array: {array}")

array: [0.21337097 0.94225338 0.1612848  0.27971672 0.2787665  0.00297656
 0.13895524 0.89245169 0.3056541  0.03633534]
sorted array: [0.94225338 0.89245169 0.3056541  0.27971672 0.2787665  0.21337097
 0.1612848  0.13895524 0.03633534 0.00297656]


In [24]:
#1.3.6
import numpy as np
array = np.random.random((3, 5, 4, 5))
print(f"shape: {array.shape}\ndims: {array.ndim}\nsize: {array.size}")

shape: (3, 5, 4, 5)
dims: 4
size: 300


In [5]:
#2.3.1
import numpy as np
import pandas as pd
series1 = pd.Series(np.random.random(5))
series2 = pd.Series(np.random.random(5))
print(sum((series1-series2)**2)**0.5)

0.9812898337988617


In [7]:
#2.3.2
import pandas as pd
dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/adult.csv")
print(dataframe.head(2))

   age  workclass  education_num marital_status    occupation   relationship  \
0   39  State-gov             13  Never-married  Adm-clerical  Not-in-family   

    race gender  hours_per_week native_country  capital income_status  
0  White   Male              40  United-States     2174         <=50K  


In [34]:
#2.3.3
import pandas as pd
dataframe = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/main/adult.csv")
print(dataframe.head(2))
print("-"*50)
print(dataframe.tail(3))
print("-"*50)
print(dataframe.shape)
print("-"*50)
print(dataframe.describe())
print("-"*50)
print(dataframe.iloc[1:3])
print("-"*50)
print(dataframe[dataframe["age"] > 50].head(2))
print("-"*50)

   age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K  
--------------------------------------------------
       age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male  

In [40]:
#3.3.2
import pandas as pd
from sklearn import preprocessing

df = pd.read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")

# нормализацию первого числового признака
# (sepal_length_cm) с использованием минимаксного преобразования
scaler = preprocessing.MinMaxScaler()
df[["sepal_length_cm"]] = scaler.fit_transform(df[["sepal_length_cm"]])

# (sepal_width_cm) с задействованием z-масштабирования.
scaler = preprocessing.StandardScaler()
df[["sepal_width_cm"]] = scaler.fit_transform(df[["sepal_width_cm"]])

df.head()

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa